import {
    AlignJustify, LampCeiling, Triangle, Fan, PlugZap, Lightbulb,
    PanelsTopLeft, Table2, Lamp, CloudRain, Search, BoxSelect
} from 'lucide-react'
import { Banner } from '../components/main/hero/HeroCarousel';
import { CatItem } from '../components/main/category/CategoryGrid';
import { Product } from '../components/main/product/ProductCarousel';

export const CONTACTS = [
    { label: "TP.Hồ Chí Minh:", phone: "0853892898", note: "Chi Nhánh Chính" },
];


export const CATEGORY_ITEMS = [
    { icon: AlignJustify, label: 'Tất cả SP', img: '/den-sai-gon/icons/icon-1.png' },
    { icon: LampCeiling, label: 'Đèn âm trần', img: '/den-sai-gon/icons/icon-03.png' },
    { icon: Triangle, label: 'Đèn chùm', img: '/den-sai-gon/icons/icon-08.png' },
    { icon: Fan, label: 'Quạt trần', img: '/den-sai-gon/icons/icon-04.png' },
    { icon: PlugZap, label: 'Đèn thả', img: '/den-sai-gon/icons/icon-09.png' },
    { icon: Lightbulb, label: 'Đèn tường', img: '/den-sai-gon/icons/icon-06.png' },
    { icon: PanelsTopLeft, label: 'Đèn rọi ray', img: '/den-sai-gon/icons/icon-05 (1).png' },
    { icon: Table2, label: 'Đèn LED panel', img: '/den-sai-gon/icons/icon-02.png' },
    { icon: Lamp, label: 'Đèn bàn, Đèn cây', img: '/den-sai-gon/icons/icon-10.png' },
    { label: 'Đèn LED pha', img: '/den-sai-gon/icons/icon2-10.svg' },
    { icon: CloudRain, label: 'Đèn ngoài trời', img: '/den-sai-gon/icons/icon-07.png' },

]

export const BANNERS: Banner[] = [
    { src: '/den-sai-gon/banners/banner1.jpg', alt: 'Khuyến mãi 1' },
    { src: '/den-sai-gon/banners/banner2.jpg', alt: 'Khuyến mãi 2' },
]

export const ITEMS: CatItem[] = [
    { title: 'Đèn LED âm trần', image: '/den-sai-gon/hinh-anh/am_tran.png' },
    { title: 'Đèn chùm', image: '/den-sai-gon/hinh-anh/den_chum.png' },
    { title: 'Đèn thả', image: '/den-sai-gon/hinh-anh/den_tha.png' },
    { title: 'Đèn LED ốp trần', image: '/den-sai-gon/hinh-anh/op_tran.png' },
    { title: 'Quạt trần', image: '/den-sai-gon/hinh-anh/quat-tran-5canh.jpg' },
    { title: 'Đèn LED panel', image: '/den-sai-gon/hinh-anh/pane.png' },
    { title: 'Đèn LED dây', image: '/den-sai-gon/hinh-anh/day_led_day.jpg' },
    { title: 'Đèn tuýp LED', image: '/den-sai-gon/hinh-anh/den_tuyp_led.png' },
    { title: 'Bóng đèn LED', image: '/den-sai-gon/hinh-anh/den_trong_nha.png' },
    { title: 'Đèn LED rọi ray', image: '/den-sai-gon/hinh-anh/den_roi_ray.png' },
    { title: 'Đèn tường', image: '/den-sai-gon/hinh-anh/den-tuong.jpg' },
    { title: 'Đèn bàn', image: '/den-sai-gon/hinh-anh/den_ban.png' },
    { title: 'Đèn cây', image: '/den-sai-gon/hinh-anh/den_cay.jpg' },
    { title: 'Đèn LED pha', image: '/den-sai-gon/hinh-anh/den_pha_led.png' },
    { title: 'Đèn sân vườn', image: '/den-sai-gon/hinh-anh/den_san_vuon.png' },
    { title: 'Đèn rọi ngoài trời', image: '/den-sai-gon/hinh-anh/den_roi_ngoai_troi.png' },
    { title: 'Đèn thả văn phòng', image: '/den-sai-gon/hinh-anh/pane.png' },
    { title: 'Thiết bị điện', image: '/den-sai-gon/hinh-anh/aptomat.png' },
]

export const PRODUCTSLEDAMTRAN: Product[] = [
    {
        id: 105305439,
        title: 'Đèn LED âm trần 9W',
        image: '/den-sai-gon/anh-sp/led-am-tran.png',
        priceMin: 129000,
        priceMax: 159000,
        discount: 15,
        isDownlight: true,
        variants: [
            { image: '/den-sai-gon/anh-sp/led-am-tran.png', thumb: '/den-sai-gon/anh-sp/led-am-tran.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-2.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-2.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-3.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-3.png', label: '7W-D55/Ánh sáng trắng 3000K' },
        ],
    },
    {
        id: 593958348,
        title: 'Đèn LED âm trần Spotlight Chống Chói X7 - BrightLux',
        image: '/den-sai-gon/anh-sp/led-am-tran.png',
        priceMin: 129000,
        priceMax: 159000,
        discount: 15,
        isDownlight: true,
        variants: [
            { image: '/den-sai-gon/anh-sp/led-am-tran.png', thumb: '/den-sai-gon/anh-sp/led-am-tran.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-2.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-2.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-3.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-3.png', label: '7W-D55/Ánh sáng trắng 3000K' },
        ],
    },
    {
        id: 1936939583,
        title: 'Đèn LED âm trần 9W',
        image: '/den-sai-gon/anh-sp/led-am-tran.png',
        priceMin: 129000,
        priceMax: 159000,
        discount: 15,
        isDownlight: true,
        variants: [
            { image: '/den-sai-gon/anh-sp/led-am-tran.png', thumb: '/den-sai-gon/anh-sp/led-am-tran.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-2.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-2.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-3.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-3.png', label: '7W-D55/Ánh sáng trắng 3000K' },
        ],
    },
    {
        id: 124325439,
        title: 'Đèn LED âm trần 9W',
        image: '/den-sai-gon/anh-sp/led-am-tran.png',
        priceMin: 129000,
        priceMax: 159000,
        discount: 15,
        isDownlight: true,
        variants: [
            { image: '/den-sai-gon/anh-sp/led-am-tran.png', thumb: '/den-sai-gon/anh-sp/led-am-tran.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-2.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-2.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-3.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-3.png', label: '7W-D55/Ánh sáng trắng 3000K' },
        ],
    },
    {
        id: 163575765,
        title: 'Đèn LED âm trần 9W',
        image: '/den-sai-gon/anh-sp/led-am-tran.png',
        priceMin: 129000,
        priceMax: 159000,
        discount: 15,
        isDownlight: true,
        variants: [
            { image: '/den-sai-gon/anh-sp/led-am-tran.png', thumb: '/den-sai-gon/anh-sp/led-am-tran.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-2.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-2.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-3.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-3.png', label: '7W-D55/Ánh sáng trắng 3000K' },
        ],
    },
    {
        id: 1243253,
        title: 'Đèn LED âm trần 9W',
        image: '/den-sai-gon/anh-sp/led-am-tran.png',
        priceMin: 129000,
        priceMax: 159000,
        discount: 15,
        isDownlight: true,
        variants: [
            { image: '/den-sai-gon/anh-sp/led-am-tran.png', thumb: '/den-sai-gon/anh-sp/led-am-tran.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-2.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-2.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-3.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-3.png', label: '7W-D55/Ánh sáng trắng 3000K' },
        ],
    },
    {
        id: 142345535,
        title: 'Đèn LED âm trần 9W',
        image: '/den-sai-gon/anh-sp/led-am-tran.png',
        priceMin: 129000,
        priceMax: 159000,
        discount: 15,
        isDownlight: true,
        variants: [
            { image: '/den-sai-gon/anh-sp/led-am-tran.png', thumb: '/den-sai-gon/anh-sp/led-am-tran.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-2.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-2.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-3.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-3.png', label: '7W-D55/Ánh sáng trắng 3000K' },
        ],
    },
    {
        id: 11232131251,
        title: 'Đèn LED âm trần 9W',
        image: '/den-sai-gon/anh-sp/led-am-tran.png',
        priceMin: 129000,
        priceMax: 159000,
        discount: 15,
        isDownlight: true,
        variants: [
            { image: '/den-sai-gon/anh-sp/led-am-tran.png', thumb: '/den-sai-gon/anh-sp/led-am-tran.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-2.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-2.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-3.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-3.png', label: '7W-D55/Ánh sáng trắng 3000K' },
        ],
    },
    {
        id: 112312321,
        title: 'Đèn LED âm trần 9W',
        image: '/den-sai-gon/anh-sp/led-am-tran.png',
        priceMin: 129000,
        priceMax: 159000,
        discount: 15,
        isDownlight: true,
        variants: [
            { image: '/den-sai-gon/anh-sp/led-am-tran.png', thumb: '/den-sai-gon/anh-sp/led-am-tran.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-2.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-2.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-3.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-3.png', label: '7W-D55/Ánh sáng trắng 3000K' },
        ],
    },
    {
        id: 112312322,
        title: 'Đèn LED âm trần 9W',
        image: '/den-sai-gon/anh-sp/led-am-tran.png',
        priceMin: 129000,
        priceMax: 159000,
        discount: 15,
        isDownlight: true,
        variants: [
            { image: '/den-sai-gon/anh-sp/led-am-tran.png', thumb: '/den-sai-gon/anh-sp/led-am-tran.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-2.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-2.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-3.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-3.png', label: '7W-D55/Ánh sáng trắng 3000K' },
        ],
    },
    {
        id: 112312323,
        title: 'Đèn LED âm trần 9W',
        image: '/den-sai-gon/anh-sp/led-am-tran.png',
        priceMin: 129000,
        priceMax: 159000,
        discount: 15,
        isDownlight: true,
        variants: [
            { image: '/den-sai-gon/anh-sp/led-am-tran.png', thumb: '/den-sai-gon/anh-sp/led-am-tran.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-2.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-2.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-3.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-3.png', label: '7W-D55/Ánh sáng trắng 3000K' },
        ],
    },
    {
        id: 112312324,
        title: 'Đèn LED âm trần 9W',
        image: '/den-sai-gon/anh-sp/led-am-tran.png',
        priceMin: 129000,
        priceMax: 159000,
        discount: 15,
        isDownlight: true,
        variants: [
            { image: '/den-sai-gon/anh-sp/led-am-tran.png', thumb: '/den-sai-gon/anh-sp/led-am-tran.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-2.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-2.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-3.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-3.png', label: '7W-D55/Ánh sáng trắng 3000K' },
        ],
    },
    {
        id: 112312325,
        title: 'Đèn LED âm trần 9W',
        image: '/den-sai-gon/anh-sp/led-am-tran.png',
        priceMin: 129000,
        priceMax: 159000,
        discount: 15,
        isDownlight: true,
        variants: [
            { image: '/den-sai-gon/anh-sp/led-am-tran.png', thumb: '/den-sai-gon/anh-sp/led-am-tran.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-2.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-2.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-3.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-3.png', label: '7W-D55/Ánh sáng trắng 3000K' },
        ],
    },
    {
        id: 112312325,
        title: 'Đèn LED âm trần 9W',
        image: '/den-sai-gon/anh-sp/led-am-tran.png',
        priceMin: 129000,
        priceMax: 159000,
        discount: 15,
        isDownlight: true,
        variants: [
            { image: '/den-sai-gon/anh-sp/led-am-tran.png', thumb: '/den-sai-gon/anh-sp/led-am-tran.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-2.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-2.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-3.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-3.png', label: '7W-D55/Ánh sáng trắng 3000K' },
        ],
    },
    {
        id: 112312325,
        title: 'Đèn LED âm trần 9W',
        image: '/den-sai-gon/anh-sp/led-am-tran.png',
        priceMin: 129000,
        priceMax: 159000,
        discount: 15,
        isDownlight: true,
        variants: [
            { image: '/den-sai-gon/anh-sp/led-am-tran.png', thumb: '/den-sai-gon/anh-sp/led-am-tran.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-2.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-2.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-3.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-3.png', label: '7W-D55/Ánh sáng trắng 3000K' },
        ],
    },
    {
        id: 112312325,
        title: 'Đèn LED âm trần 9W',
        image: '/den-sai-gon/anh-sp/led-am-tran.png',
        priceMin: 129000,
        priceMax: 159000,
        discount: 15,
        isDownlight: true,
        variants: [
            { image: '/den-sai-gon/anh-sp/led-am-tran.png', thumb: '/den-sai-gon/anh-sp/led-am-tran.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-2.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-2.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-3.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-3.png', label: '7W-D55/Ánh sáng trắng 3000K' },
        ],
    },
    {
        id: 112312325,
        title: 'Đèn LED âm trần 9W',
        image: '/den-sai-gon/anh-sp/led-am-tran.png',
        priceMin: 129000,
        priceMax: 159000,
        discount: 15,
        isDownlight: true,
        variants: [
            { image: '/den-sai-gon/anh-sp/led-am-tran.png', thumb: '/den-sai-gon/anh-sp/led-am-tran.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-2.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-2.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-3.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-3.png', label: '7W-D55/Ánh sáng trắng 3000K' },
        ],
    },
    {
        id: 112312325,
        title: 'Đèn LED âm trần 9W',
        image: '/den-sai-gon/anh-sp/led-am-tran.png',
        priceMin: 129000,
        priceMax: 159000,
        discount: 15,
        isDownlight: true,
        variants: [
            { image: '/den-sai-gon/anh-sp/led-am-tran.png', thumb: '/den-sai-gon/anh-sp/led-am-tran.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-2.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-2.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-3.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-3.png', label: '7W-D55/Ánh sáng trắng 3000K' },
        ],
    },
    {
        id: 112312325,
        title: 'Đèn LED âm trần 9W',
        image: '/den-sai-gon/anh-sp/led-am-tran.png',
        priceMin: 129000,
        priceMax: 159000,
        discount: 15,
        isDownlight: true,
        variants: [
            { image: '/den-sai-gon/anh-sp/led-am-tran.png', thumb: '/den-sai-gon/anh-sp/led-am-tran.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-2.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-2.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-3.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-3.png', label: '7W-D55/Ánh sáng trắng 3000K' },
        ],
    },
    {
        id: 112312325,
        title: 'Đèn LED âm trần 9W',
        image: '/den-sai-gon/anh-sp/led-am-tran.png',
        priceMin: 129000,
        priceMax: 159000,
        discount: 15,
        isDownlight: true,
        variants: [
            { image: '/den-sai-gon/anh-sp/led-am-tran.png', thumb: '/den-sai-gon/anh-sp/led-am-tran.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-2.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-2.png', label: '7W-D55/Ánh sáng trắng 3000K' },
            { image: '/den-sai-gon/anh-sp/led-am-tran-3.png', thumb: '/den-sai-gon/anh-sp/led-am-tran-3.png', label: '7W-D55/Ánh sáng trắng 3000K' },
        ],
    },
]
